FROM python:3.10

WORKDIR /app

# Copier le fichier requirements.txt dans le conteneur
COPY images/python/requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt